In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset("titanic")

In [4]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [7]:
df.sample(7)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
368,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
809,1,1,female,33.0,1,0,53.1000,S,First,woman,False,E,Southampton,yes,False
852,0,3,female,9.0,1,1,15.2458,C,Third,child,False,NaN,Cherbourg,no,False
798,0,3,male,30.0,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
181,0,2,male,NaN,0,0,15.0500,C,Second,man,True,NaN,Cherbourg,no,True
287,0,3,male,22.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True

In [8]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [10]:
df.drop([ 'deck', 'embark_town','alive', 'class','who','adult_male'], axis = 1, inplace = True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [12]:
df['age'].fillna(df['age'].mean(), inplace = True)

In [13]:
df.dropna(subset=['embarked'], inplace = True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [15]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.000000,1,0,7.2500,S,False
1,1,1,female,38.000000,1,0,71.2833,C,False
2,1,3,female,26.000000,0,0,7.9250,S,True
3,1,1,female,35.000000,1,0,53.1000,S,False
4,0,3,male,35.000000,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,True
887,1,1,female,19.000000,0,0,30.0000,S,True
888,0,3,female,29.699118,1,2,23.4500,S,False
889,1,1,male,26.000000,0,0,30.0000,C,True
890,0,3,male,32.000000,0,0,7.7500,Q,True

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [17]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [18]:
df['sex'] = le.fit_transform(df['sex'])

In [19]:
df['embarked'] = le.fit_transform(df['embarked'])

In [20]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2  False
1         1       1    0  38.0      1      0  71.2833         0  False
2         1       3    0  26.0      0      0   7.9250         2   True
3         1       1    0  35.0      1      0  53.1000         2  False
4         0       3    1  35.0      0      0   8.0500         2   True

In [21]:
df = df.astype(int)

In [22]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [23]:
X = df.drop("survived",axis = 1)
y = df['survived']

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# logistic regression

In [25]:
# use logistic regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [26]:
model.fit(X_train,y_train)

LogisticRegression()

# Prediction

In [27]:
y_pred = model.predict(X_test)

In [28]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0])

In [29]:
# real data
y_test

281    0
435    1
39     1
418    0
585    1
      ..
711    0
840    0
381    1
141    1
174    0
Name: survived, Length: 294, dtype: int64

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [31]:
accuracy_score(y_test,y_pred)

0.8163265306122449

In [32]:
confusion_matrix(y_test,y_pred)

array([[157,  27],
       [ 27,  83]])

In [33]:
# classificatio report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       184
           1       0.75      0.75      0.75       110

    accuracy                           0.82       294
   macro avg       0.80      0.80      0.80       294
weighted avg       0.82      0.82      0.82       294

# KNN (K-nearest Neighboar)

In [34]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [35]:
X_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
6         1    1   54      0      0    51         2      1
576       2    0   34      0      0    13         2      1
445       1    1    4      0      2    81         2      0
74        3    1   32      0      0    56         2      1
670       2    0   40      1      1    39         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
107       3    1   29      0      0     7         2      1
271       3    1   25      0      0     0         2      1
862       1    0   48      0      0    25         2      1
436       3    0   21      2      2    34         2      0
103       3    1   33      0      0     8         2      1

[595 rows x 8 columns]

In [36]:
y_train

6      0
576    1
445    1
74     1
670    1
      ..
107    1
271    1
862    1
436    0
103    0
Name: survived, Length: 595, dtype: int64

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
scaler = StandardScaler()

In [39]:
X_train_scale = scaler.fit_transform(X_train)
X_train_scale

array([[-1.60124536,  0.71693438,  1.82943665, ...,  0.36229213,
         0.58362385,  0.82798092],
       [-0.39524411, -1.39482779,  0.3172955 , ..., -0.37587359,
         0.58362385,  0.82798092],
       [-1.60124536,  0.71693438, -1.95091623, ...,  0.94505454,
         0.58362385, -1.2077573 ],
       ...,
       [-1.60124536, -1.39482779,  1.37579431, ..., -0.14276863,
         0.58362385,  0.82798092],
       [ 0.81075714, -1.39482779, -0.66559625, ...,  0.03206009,
         0.58362385, -1.2077573 ],
       [ 0.81075714,  0.71693438,  0.24168844, ..., -0.47300066,
         0.58362385,  0.82798092]], shape=(595, 8))

In [40]:
X_test_scaled = scaler.fit_transform(X_test)

In [41]:
X_test_scaled

array([[ 0.85497773,  0.77319214, -0.07093214, ..., -0.50920099,
         0.59339083,  0.78446454],
       [-1.5163756 , -1.29333958, -1.19817798, ...,  1.95858534,
         0.59339083, -1.27475488],
       [ 0.85497773, -1.29333958, -1.19817798, ..., -0.42184572,
        -1.89885065, -1.27475488],
       ...,
       [ 0.85497773, -1.29333958, -2.24490626, ..., -0.33449045,
        -1.89885065, -1.27475488],
       [ 0.85497773, -1.29333958, -0.5540375 , ..., -0.50920099,
         0.59339083,  0.78446454],
       [-1.5163756 ,  0.77319214,  2.18355955, ..., -0.0069082 ,
        -1.89885065,  0.78446454]], shape=(294, 8))

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(X_train_scale,y_train)

KNeighborsClassifier()

In [43]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [44]:
accuracy_score(y_test,y_pred_knn)

0.8061224489795918

In [45]:
confusion_matrix(y_test,y_pred_knn)

array([[158,  26],
       [ 31,  79]])

In [46]:
# classificatio report
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85       184
           1       0.75      0.72      0.73       110

    accuracy                           0.81       294
   macro avg       0.79      0.79      0.79       294
weighted avg       0.80      0.81      0.81       294

# Naive Bayes Implementation

In [47]:
X_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
711       1    1   29      0      0    26         2      1
840       3    1   20      0      0     7         2      1
381       3    0    1      0      2    15         0      0
141       3    0   22      0      0     7         2      1
174       1    1   56      0      0    30         0      1

[294 rows x 8 columns]

In [48]:
X_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
6         1    1   54      0      0    51         2      1
576       2    0   34      0      0    13         2      1
445       1    1    4      0      2    81         2      0
74        3    1   32      0      0    56         2      1
670       2    0   40      1      1    39         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
107       3    1   29      0      0     7         2      1
271       3    1   25      0      0     0         2      1
862       1    0   48      0      0    25         2      1
436       3    0   21      2      2    34         2      0
103       3    1   33      0      0     8         2      1

[595 rows x 8 columns]

In [49]:
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()

In [50]:
model_NB.fit(X_train, y_train)

GaussianNB()

In [51]:
y_pred_NB = model_NB.predict(X_test)

In [52]:
X_test_scaled

array([[ 0.85497773,  0.77319214, -0.07093214, ..., -0.50920099,
         0.59339083,  0.78446454],
       [-1.5163756 , -1.29333958, -1.19817798, ...,  1.95858534,
         0.59339083, -1.27475488],
       [ 0.85497773, -1.29333958, -1.19817798, ..., -0.42184572,
        -1.89885065, -1.27475488],
       ...,
       [ 0.85497773, -1.29333958, -2.24490626, ..., -0.33449045,
        -1.89885065, -1.27475488],
       [ 0.85497773, -1.29333958, -0.5540375 , ..., -0.50920099,
         0.59339083,  0.78446454],
       [-1.5163756 ,  0.77319214,  2.18355955, ..., -0.0069082 ,
        -1.89885065,  0.78446454]], shape=(294, 8))

In [53]:
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1])

In [54]:
accuracy_score(y_test,y_pred_NB)

0.7789115646258503

In [55]:
confusion_matrix(y_test,y_pred_NB)

array([[145,  39],
       [ 26,  84]])

In [56]:
# classificatio report
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.79      0.82       184
           1       0.68      0.76      0.72       110

    accuracy                           0.78       294
   macro avg       0.77      0.78      0.77       294
weighted avg       0.79      0.78      0.78       294

# Decision Trees

In [57]:
from sklearn.tree import DecisionTreeClassifier
model_DT = DecisionTreeClassifier()

In [58]:
model_DT.fit(X_train_scale,y_train)

DecisionTreeClassifier()

In [59]:
y_pred_DT = model.predict(X_test)

In [60]:
y_pred_DT

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0])

In [61]:
accuracy_score(y_test,y_pred_DT)

0.8163265306122449

In [62]:
confusion_matrix(y_test,y_pred_DT)

array([[157,  27],
       [ 27,  83]])

In [63]:
# classificatio report
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       184
           1       0.75      0.75      0.75       110

    accuracy                           0.82       294
   macro avg       0.80      0.80      0.80       294
weighted avg       0.82      0.82      0.82       294

# SVM (Support Vector Machine)

In [64]:
from sklearn.svm import SVC
model_svm = SVC(kernel  = 'rbf')

In [65]:
model_svm.fit(X_train_scale,y_train)

SVC()

In [66]:
y_pred_svc = model_svm.predict(X_test_scaled)

In [67]:
y_pred_svc

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0])

In [68]:
accuracy_score(y_test,y_pred_svc)

0.8197278911564626

In [69]:
confusion_matrix(y_test,y_pred_svc)

array([[160,  24],
       [ 29,  81]])

In [70]:
# classificatio report
print(classification_report(y_test,y_pred_svc))

              precision    recall  f1-score   support

           0       0.85      0.87      0.86       184
           1       0.77      0.74      0.75       110

    accuracy                           0.82       294
   macro avg       0.81      0.80      0.81       294
weighted avg       0.82      0.82      0.82       294

# ALL are ussing in One frame

In [71]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [72]:
X1 = df.drop("survived",axis = 1)
y1 = df['survived']

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.33, random_state=42)

In [74]:
# feature scaleing
scaler =  StandardScaler()
x_train_scale1 = scaler.fit_transform(X_train)
x_test_scale1 = scaler.fit_transform(X_test)

In [75]:
models = {
    "logistic Regresion" : LogisticRegression(),
    "KNN" :KNeighborsClassifier(),
    "Naive Byeas": GaussianNB(),
    "Decision tree" : DecisionTreeClassifier(),
    "SVM": SVC()
}

In [76]:
result = []

In [77]:
for name, model in models.items():
    # Train the model
    model.fit(x_train_scale1, y_train)

    # Make predictions
    y_pred = model.predict(x_test_scale1)

    # Calculate metrics
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Store results
    result.append({
        'Model': name,
        'Accuracy': round(acc, 4),
        'F1_Score': round(f1, 4),
    })

In [78]:
result

[{'Model': 'logistic Regresion', 'Accuracy': 0.8095, 'F1_Score': 0.7407},
 {'Model': 'KNN', 'Accuracy': 0.8061, 'F1_Score': 0.7349},
 {'Model': 'Naive Byeas', 'Accuracy': 0.7755, 'F1_Score': 0.7155},
 {'Model': 'Decision tree', 'Accuracy': 0.7789, 'F1_Score': 0.6766},
 {'Model': 'SVM', 'Accuracy': 0.8197, 'F1_Score': 0.7535}]

# use KNN model it gives higest accuray 81 % use it

# use in Binary form

In [79]:
import joblib
joblib.dump(models['KNN'],'KNN_titanic.pkl')
joblib.dump(scaler,'scaler.pkl')
joblib.dump(X.columns.tolist(),'columns.pkl')

['columns.pkl']

# Apply Cross Validation

In [80]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [81]:
X = df.drop("survived",axis = 1)
y = df['survived']

In [82]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

In [83]:
scaler = StandardScaler()

In [87]:
X_scaled = scaler.fit_transform(X)

In [91]:
scores = cross_val_score(model_svm, X_scaled, y, cv=5, scoring='accuracy')

In [92]:
print(scores)

[0.83146067 0.82022472 0.81460674 0.80898876 0.86440678]

In [93]:
print(scores.mean())

0.8279375357074844

## Can also use other alogorith

In [102]:
scores1 = cross_val_score(model_DT, X_scaled, y, cv=5, scoring='accuracy')

In [107]:
print(scores1)

[0.75842697 0.81460674 0.80337079 0.79213483 0.81920904]

In [108]:
print(scores1.mean())

0.7975496730781438

In [106]:
scores2 = cross_val_score(model_NB, X_scaled, y, cv=5, scoring='accuracy')

In [109]:
print(scores2)

[0.73033708 0.78651685 0.81460674 0.78651685 0.80225989]

In [110]:
print(scores2.mean())

0.7840474830191074

In [112]:
scores3 = cross_val_score(model, X_scaled, y, cv=5, scoring='accuracy')

In [113]:
print(scores3)

[0.83146067 0.82022472 0.81460674 0.80898876 0.86440678]

In [114]:
print(scores3.mean())

0.8279375357074844

In [115]:
scores4 = cross_val_score(knn_model, X_scaled, y, cv=5, scoring='accuracy')

In [116]:
print(scores4)

[0.78651685 0.76404494 0.8258427  0.81460674 0.80225989]

In [117]:
print(scores4.mean())

0.7986542245921411