# Data Gathering

# 1. Importing Pandas

In [1]:
import pandas as pd

# 2. Opening Local Csv file

In [2]:
df = pd.read_csv(r"ml_student_dataset.csv")
df

,student_id,age,study_hours_per_day,attendance_percent,assignments_completed,passed_exam
0,1,58,2,51,4,0
1,2,33,4,58,1,0
2,3,52,2,87,6,0
3,4,20,1,55,3,0
4,5,32,9,88,0,0
...,...,...,...,...,...,...
95,96,57,9,50,10,0
96,97,53,5,92,1,0
97,98,26,5,57,1,0
98,99,53,3,67,4,0
99,100,56,4,95,5,0

# 3. Opening a csv file from URL

In [3]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df1 = pd.read_csv(url)
df1

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# 4. Sep Parameter

In [4]:
sept = pd.read_csv(r"Sep_Parameter.csv")
sept

          name;age;city
0        John;25;Mumbai
1        Alice;30;Delhi
2         Rahul;28;Pune
3     Sara;22;Bengaluru
4     Amit;27;Hyderabad
5      Priya;24;Chennai
6      Rohan;29;Kolkata
7     Neha;26;Ahmedabad
8       Vikas;31;Jaipur
9       Anjali;23;Surat
10      Karan;28;Mumbai
11       Pooja;25;Delhi
12        Arjun;32;Pune
13   Sneha;27;Bengaluru
14  Manish;30;Hyderabad
15     Kavya;24;Chennai
16    Deepak;29;Kolkata
17   Nisha;26;Ahmedabad
18      Akash;33;Jaipur
19        Ritu;22;Surat
20      Varun;28;Mumbai
21       Meera;25;Delhi
22       Sanjay;31;Pune
23    Isha;24;Bengaluru
24  Rakesh;30;Hyderabad
25     Divya;23;Chennai
26    Aditya;27;Kolkata
27  Shreya;26;Ahmedabad
28      Nitin;29;Jaipur
29      Ayesha;25;Surat

In [5]:
sept = pd.read_csv(r"Sep_Parameter.csv", sep = ";")
sept

      name  age       city
0     John   25     Mumbai
1    Alice   30      Delhi
2    Rahul   28       Pune
3     Sara   22  Bengaluru
4     Amit   27  Hyderabad
5    Priya   24    Chennai
6    Rohan   29    Kolkata
7     Neha   26  Ahmedabad
8    Vikas   31     Jaipur
9   Anjali   23      Surat
10   Karan   28     Mumbai
11   Pooja   25      Delhi
12   Arjun   32       Pune
13   Sneha   27  Bengaluru
14  Manish   30  Hyderabad
15   Kavya   24    Chennai
16  Deepak   29    Kolkata
17   Nisha   26  Ahmedabad
18   Akash   33     Jaipur
19    Ritu   22      Surat
20   Varun   28     Mumbai
21   Meera   25      Delhi
22  Sanjay   31       Pune
23    Isha   24  Bengaluru
24  Rakesh   30  Hyderabad
25   Divya   23    Chennai
26  Aditya   27    Kolkata
27  Shreya   26  Ahmedabad
28   Nitin   29     Jaipur
29  Ayesha   25      Surat

# 5. Index_col Parsmeter

In [6]:
idx_col = pd.read_csv(r"index_col_dataset_25.csv",)
idx_col

    student_id        name  age  marks
0            1   Student_1   19     61
1            2   Student_2   20     62
2            3   Student_3   21     63
3            4   Student_4   22     64
4            5   Student_5   23     65
5            6   Student_6   24     66
6            7   Student_7   25     67
7            8   Student_8   18     68
8            9   Student_9   19     69
9           10  Student_10   20     70
10          11  Student_11   21     71
11          12  Student_12   22     72
12          13  Student_13   23     73
13          14  Student_14   24     74
14          15  Student_15   25     75
15          16  Student_16   18     76
16          17  Student_17   19     77
17          18  Student_18   20     78
18          19  Student_19   21     79
19          20  Student_20   22     80
20          21  Student_21   23     81
21          22  Student_22   24     82
22          23  Student_23   25     83
23          24  Student_24   18     84
24          25  Student_25   19     85

In [7]:
idx_col = pd.read_csv(r"index_col_dataset_25.csv",index_col="student_id")
idx_col

                  name  age  marks
student_id
1            Student_1   19     61
2            Student_2   20     62
3            Student_3   21     63
4            Student_4   22     64
5            Student_5   23     65
6            Student_6   24     66
7            Student_7   25     67
8            Student_8   18     68
9            Student_9   19     69
10          Student_10   20     70
11          Student_11   21     71
12          Student_12   22     72
13          Student_13   23     73
14          Student_14   24     74
15          Student_15   25     75
16          Student_16   18     76
17          Student_17   19     77
18          Student_18   20     78
19          Student_19   21     79
20          Student_20   22     80
21          Student_21   23     81
22          Student_22   24     82
23          Student_23   25     83
24          Student_24   18     84
25          Student_25   19     85

# 6. Header Parameter

Header Parameter Concepts
Parameter	   Meaning
header=0	   First row is column names (default)
header=None    No header row exists
header=1	   Second row is column names
header=2	   Third row is column names

In [8]:
hed_P= pd.read_csv(r"header_parameter_dataset.csv")
print(hed_P)

    John  25     Mumbai
0  Alice  30      Delhi
1  Rahul  28       Pune
2   Sara  22  Bengaluru
3   Amit  27  Hyderabad

In [9]:

hed_pu = pd.read_csv(
    "header_parameter_dataset.csv",
    header=None
)

print(hed_pu)

       0   1          2
0   John  25     Mumbai
1  Alice  30      Delhi
2  Rahul  28       Pune
3   Sara  22  Bengaluru
4   Amit  27  Hyderabad

In [10]:
hed_use = pd.read_csv(
    "header_parameter_dataset.csv",
    header=None,
    names=["Name", "Age", "City"]
)

print(hed_use)

    Name  Age       City
0   John   25     Mumbai
1  Alice   30      Delhi
2  Rahul   28       Pune
3   Sara   22  Bengaluru
4   Amit   27  Hyderabad

In [11]:
# 7. Use_cols parameter
pd.read_csv(r"ml_student_dataset.csv", usecols = ['student_id','age','attendance_percent','assignments_completed'])

    student_id  age  attendance_percent  assignments_completed
0            1   58                  51                      4
1            2   33                  58                      1
2            3   52                  87                      6
3            4   20                  55                      3
4            5   32                  88                      0
..         ...  ...                 ...                    ...
95          96   57                  50                     10
96          97   53                  92                      1
97          98   26                  57                      1
98          99   53                  67                      4
99         100   56                  95                      5

[100 rows x 4 columns]

In [12]:
df

,student_id,age,study_hours_per_day,attendance_percent,assignments_completed,passed_exam
0,1,58,2,51,4,0
1,2,33,4,58,1,0
2,3,52,2,87,6,0
3,4,20,1,55,3,0
4,5,32,9,88,0,0
...,...,...,...,...,...,...
95,96,57,9,50,10,0
96,97,53,5,92,1,0
97,98,26,5,57,1,0
98,99,53,3,67,4,0
99,100,56,4,95,5,0

In [13]:
import pandas as pd

# skiprows/nrows parameter

In [14]:
# skip row  
pd.read_csv(r"ml_student_dataset.csv",skiprows= [0,1])

      2  33  4  58   1  0
0     3  52  2  87   6  0
1     4  20  1  55   3  0
2     5  32  9  88   0  0
3     6  53  4  95  10  0
4     7  52  7  64   7  0
..  ...  .. ..  ..  .. ..
93   96  57  9  50  10  0
94   97  53  5  92   1  0
95   98  26  5  57   1  0
96   99  53  3  67   4  0
97  100  56  4  95   5  0

[98 rows x 6 columns]

In [15]:
pd.read_csv(r"ml_student_dataset.csv",nrows = 20)

,student_id,age,study_hours_per_day,attendance_percent,assignments_completed,passed_exam
0,1,58,2,51,4,0
1,2,33,4,58,1,0
2,3,52,2,87,6,0
3,4,20,1,55,3,0
4,5,32,9,88,0,0
5,6,53,4,95,10,0
6,7,52,7,64,7,0
7,8,55,5,50,2,0
8,9,45,6,67,2,0
9,10,31,6,56,1,0
10,11,42,2,72,5,0
11,12,56,5,52,7,0
12,13,52,2,74,1,0
13,14,53,5,90,9,1
14,15,41,10,62,1,0
15,16,20,4,99,4,0
16,17,23,4,56,6,0
17,18,35,8,90,5,1
18,19,28,6,72,3,0
19,20,60,5,94,10,1

# Encoding Parameter

In [16]:
# if erroe unicodeerror
pd.read_csv(r"ml_student_dataset.csv",encoding = 'latin-1')

,student_id,age,study_hours_per_day,attendance_percent,assignments_completed,passed_exam
0,1,58,2,51,4,0
1,2,33,4,58,1,0
2,3,52,2,87,6,0
3,4,20,1,55,3,0
4,5,32,9,88,0,0
...,...,...,...,...,...,...
95,96,57,9,50,10,0
96,97,53,5,92,1,0
97,98,26,5,57,1,0
98,99,53,3,67,4,0
99,100,56,4,95,5,0

# Handling Dates

In [17]:
ls = pd.read_csv(r"Date_Operations_Dataset.csv")
handel_dates = pd.read_csv(r"Date_Operations_Dataset.csv", parse_dates =["OrderDate", "ShipDate"] )
ls

    ID   OrderDate    ShipDate  Amount
0    1  2026-01-01  2026-01-02    1000
1    2  2026-01-02  2026-01-04    1075
2    3  2026-01-03  2026-01-06    1150
3    4  2026-01-04  2026-01-08    1225
4    5  2026-01-05  2026-01-10    1300
5    6  2026-01-06  2026-01-07    1375
6    7  2026-01-07  2026-01-09    1450
7    8  2026-01-08  2026-01-11    1525
8    9  2026-01-09  2026-01-13    1600
9   10  2026-01-10  2026-01-15    1675
10  11  2026-01-11  2026-01-12    1750
11  12  2026-01-12  2026-01-14    1825
12  13  2026-01-13  2026-01-16    1900
13  14  2026-01-14  2026-01-18    1975
14  15  2026-01-15  2026-01-20    2050
15  16  2026-01-16  2026-01-17    2125
16  17  2026-01-17  2026-01-19    2200
17  18  2026-01-18  2026-01-21    2275
18  19  2026-01-19  2026-01-23    2350
19  20  2026-01-20  2026-01-25    2425
20  21  2026-01-21  2026-01-22    2500
21  22  2026-01-22  2026-01-24    2575
22  23  2026-01-23  2026-01-26    2650
23  24  2026-01-24  2026-01-28    2725
24  25  2026-01-25  2026-01-30    2800
25  26  2026-01-26  2026-01-27    2875
26  27  2026-01-27  2026-01-29    2950
27  28  2026-01-28  2026-01-31    3025
28  29  2026-01-29  2026-02-02    3100
29  30  2026-01-30  2026-02-04    3175

In [18]:
handel_dates

    ID  OrderDate   ShipDate  Amount
0    1 2026-01-01 2026-01-02    1000
1    2 2026-01-02 2026-01-04    1075
2    3 2026-01-03 2026-01-06    1150
3    4 2026-01-04 2026-01-08    1225
4    5 2026-01-05 2026-01-10    1300
5    6 2026-01-06 2026-01-07    1375
6    7 2026-01-07 2026-01-09    1450
7    8 2026-01-08 2026-01-11    1525
8    9 2026-01-09 2026-01-13    1600
9   10 2026-01-10 2026-01-15    1675
10  11 2026-01-11 2026-01-12    1750
11  12 2026-01-12 2026-01-14    1825
12  13 2026-01-13 2026-01-16    1900
13  14 2026-01-14 2026-01-18    1975
14  15 2026-01-15 2026-01-20    2050
15  16 2026-01-16 2026-01-17    2125
16  17 2026-01-17 2026-01-19    2200
17  18 2026-01-18 2026-01-21    2275
18  19 2026-01-19 2026-01-23    2350
19  20 2026-01-20 2026-01-25    2425
20  21 2026-01-21 2026-01-22    2500
21  22 2026-01-22 2026-01-24    2575
22  23 2026-01-23 2026-01-26    2650
23  24 2026-01-24 2026-01-28    2725
24  25 2026-01-25 2026-01-30    2800
25  26 2026-01-26 2026-01-27    2875
26  27 2026-01-27 2026-01-29    2950
27  28 2026-01-28 2026-01-31    3025
28  29 2026-01-29 2026-02-02    3100
29  30 2026-01-30 2026-02-04    3175

In [19]:
handel_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         30 non-null     int64
 1   OrderDate  30 non-null     datetime64[us]
 2   ShipDate   30 non-null     datetime64[us]
 3   Amount     30 non-null     int64
dtypes: datetime64[us](2), int64(2)
memory usage: 1.1 KB

In [20]:
# Convertors
sept = pd.read_csv(r"Sep_Parameter.csv", sep = ";", converters={"Name": lambda x: x.upper( )})
sept

      name  age       city
0     John   25     Mumbai
1    Alice   30      Delhi
2    Rahul   28       Pune
3     Sara   22  Bengaluru
4     Amit   27  Hyderabad
5    Priya   24    Chennai
6    Rohan   29    Kolkata
7     Neha   26  Ahmedabad
8    Vikas   31     Jaipur
9   Anjali   23      Surat
10   Karan   28     Mumbai
11   Pooja   25      Delhi
12   Arjun   32       Pune
13   Sneha   27  Bengaluru
14  Manish   30  Hyderabad
15   Kavya   24    Chennai
16  Deepak   29    Kolkata
17   Nisha   26  Ahmedabad
18   Akash   33     Jaipur
19    Ritu   22      Surat
20   Varun   28     Mumbai
21   Meera   25      Delhi
22  Sanjay   31       Pune
23    Isha   24  Bengaluru
24  Rakesh   30  Hyderabad
25   Divya   23    Chennai
26  Aditya   27    Kolkata
27  Shreya   26  Ahmedabad
28   Nitin   29     Jaipur
29  Ayesha   25      Surat

# Loading A Huge dataset in Chunks

In [21]:
ch = pd.read_csv(r"ml_student_dataset.csv",chunksize = 25)

In [22]:
for chunks in ch:
    print(chunks.shape)

(25, 6)
(25, 6)
(25, 6)
(25, 6)